name: Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the version
        id: get-tag
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./stacks/build/backend/Dockerfile
          build-args: |
            GITHUB_TOKEN=${{ secrets.PAT }}
            CACHEBUST=${{steps.get-tag.outputs.tag}}
          target: final
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/explorer:${{steps.get-tag.outputs.tag}}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/explorer:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/explorer:buildcache,mode=max
      - name: Deploy service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker service update \
              --image ${{ secrets.DOCKER_HUB_USERNAME }}/explorer:${{steps.get-tag.outputs.tag}} \
              --force explorer_application_dev_explorer